### ISSUE TITLE
Any updates for React 0.14?

### ISSUE THREAD

**Issue by joewood** [yahoo/react-cartographer#13]

**Comment by Edmondton** [comment]
hey @joewood yeah its definitely on the radar.  please file an issue and I will get on it as soon as I can.

**Comment by Edmondton** [comment]
@joewood give the latest a try now.  v0.4.0 --> updated to support react 14

**Comment by joewood** [comment]
Thanks for the super fast response @Edmondton!

**Comment by Edmondton** [comment]
closing issue, per response from @joewood
