### ISSUE TITLE
Unable to use it in react project

### ISSUE THREAD

**Issue by pke** [yahoo/react-cartographer#15]
It seems

```
import React from 'react'
import Container from 'react-container'
import Map from 'react-cartographer'

module.exports = React.createClass({
	render() {
		return (
			<Container>
				<Map
					provider='google'
				    providerKey='<>'
				    mapId='map'
				    addressLine1='701 First Avenue'
				    city='Sunnyvale'
				    state='CA'
				    country='United States'
				    zoom={15}
				    height={270}
				    width={580}
				>
				</Map>
			</Container>
		)
	}
})
```

does not work. The Map is not a React component according to console output.
I've installed with npm and used browserify to bundle all my script.s

**Comment by Edmondton** [comment]
@pke perhaps modify the import statement to be

'react-cartographer/lib/components/Map'

let me know if that works out for you.

**Comment by pke** [comment]
Works, thanks!
Any plans to support non static maps?

**Comment by Edmondton** [comment]
@pke glad it worked out for you.  I would like to get the feature for non static maps going, just need to find the time, hopefully down the road.  

have a great day
