### ISSUE TITLE
Uncaught TypeError: type.toUpperCase is not a function

### ISSUE THREAD

**Issue by mbrookes** [yahoo/react-cartographer#8]
Hi, I'm trying to get this working in Meteor. To get it to build I had to change bundle.js to:

```
module.exports = {
    components: {
        Map: require('./lib/components/Map')
    }
};
```
But I'm getting the following error in the browser:

```
Uncaught TypeError: type.toUpperCase is not a functionautoGenerateWrapperClass @ react.browserify.js:9673
getComponentClassForElement @ react.browserify.js:13709validatePropTypes @ react.browserify.js:10613
require.react/lib/ReactElementValidator.ReactElementValidator.createElement @ react.browserify.js:10660
React.createClass.render @ EmptyLayout.jsx:18
require.react/lib/ReactCompositeComponent.ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ react.browserify.js:7365
require.react/lib/ReactCompositeComponent.ReactCompositeComponentMixin._renderValidatedComponent @ react.browserify.js:7392
require.react/lib/ReactPerf.ReactPerf.measure.wrapper @ react.browserify.js:13941
require.react/lib/ReactCompositeComponent.ReactCompositeComponentMixin.mountComponent @ react.browserify.js:6813
require.react/lib/ReactPerf.ReactPerf.measure.wrapper @ react.browserify.js:13941
require.react/lib/ReactReconciler.ReactReconciler.mountComponent @ react.browserify.js:14758
mountComponentIntoNode @ react.browserify.js:12543require.react/lib/Transaction.Mixin.perform @ react.browserify.js:18604
batchedMountComponentIntoNode @ react.browserify.js:12564
require.react/lib/Transaction.Mixin.perform @ react.browserify.js:18604
require.react/lib/ReactDefaultBatchingStrategy.ReactDefaultBatchingStrategy.batchedUpdates @ react.browserify.js:9612batchedUpdates @ react.browserify.js:16619
require.react/lib/ReactMount.ReactMount._renderNewRootComponent @ react.browserify.js:12699
require.react/lib/ReactPerf.ReactPerf.measure.wrapper @ react.browserify.js:13941
require.react/lib/ReactMount.ReactMount.render @ react.browserify.js:12788
require.react/lib/ReactPerf.ReactPerf.measure.wrapper @ react.browserify.js:13941
(anonymous function) @ react_layout.js:44(anonymous function) @ react_layout.js:58
```

Any ideas?

Thanks,

**Comment by Edmondton** [comment]
hey Matt,
let me look into it and will get back to you asap.

**Comment by Edmondton** [comment]
hey @mbrookes,
I just tried it locally after removing node_modules and reinstalling.  I did not get that error.  I have seen that error before however.  Good catch on that bundle.js, I will put in a PR right now for that.

**Comment by mbrookes** [comment]
Thanks Ed - let me know if you need any more details to try to reproduce.

**Comment by Edmondton** [comment]
@mbrookes - just published v3.2 for the bundle.js, are you still getting that toUpperCase error ?  Please let me know.  Just curious if it is a dependency causing an issue

**Comment by mbrookes** [comment]
Thanks. I updated and it now build cleanly, but I'm still getting the error.

**Comment by Edmondton** [comment]
hmm, let me dig into it.

**Comment by Edmondton** [comment]
do you get the error running the example in index.jsx, npm run dev ?

**Comment by mbrookes** [comment]
Now that I think of it, there was one other thing I had to do differently:

`app.browserify.js`:
```
MapComponent = require('react-cartographer');
```

but that's standard for Meteor with cosmos:browserify

**Comment by mbrookes** [comment]
Re example - let me try.

**Comment by Edmondton** [comment]
try this.

require('react-cartographer/lib/components/Map');

**Comment by mbrookes** [comment]
Perfect, thanks! I'm now getting 

```https://maps.googleapis.com/maps/api/staticmap?center=701%20First%20Avenue%2CSunnyvale%2CCA%2CUnited%20States&size=580x270&mapType=roadmap&markers=color%3Apurple%7Clabel%3A1%7C701%20First%20Avenue%2CSunnyvale%2CCA%2CUnited%20States&zoom=15&key=AAAA
Failed to load resource: the server responded with a status of 403 (Forbidden)
```
So the react-cartographer is working - I guess I just need an API key?

**Comment by Edmondton** [comment]
which provider are you using ?

**Comment by Edmondton** [comment]
the google and bing versions are easy to get API keys.  I need to double check how to get a yahoo API Key

**Comment by mbrookes** [comment]
google - sorry, the markdown lost the URL for some reason. (fixed)

**Comment by mbrookes** [comment]
Working now - remembered I had put a bogus key in to see if the empty string was causing the problem.

Thanks for your help!

**Comment by Edmondton** [comment]
no problem, let me know if you have any issues

**Comment by mbrookes** [comment]
"I need to double check how to get a yahoo API Key" 

Ironic :smile: 

When I first started reading the docs, I thought it would be Yahoo on a google map, google on a bing map, and MS on a Yahoo map. One big happy family. :wink:

**Comment by mbrookes** [comment]
Went to have a look at the yahoo maps docs to see how to get an API key, but:

"We are shutting down this service. We suggest using maps from our partner Nokia. Please visit developer.here.com for more information. If you have any concerns or questions, please don't hesitate to contact us in General Discussion at YDN forum."

Guess that's why you need a component that supports other map providers! :grinning:

**Comment by Edmondton** [comment]
@mbrookes if you need a yahoo map API key, I can reach out the necesary people to get you one.
